pore.axis.perm <- read.table("pore_axis.txt", na.strings="-", header=T)
atomnames <- sapply(strsplit(colnames(pore.axis.perm),'\\.'), function(x){return(x[2])})
n.k<-sum(atomnames=="K")
col.r <- rainbow(n.k)
time <- as.numeric(rownames(pore.axis.perm))
png("pore_axis_traj.png")
plot(time, pore.axis.perm[,1],type="l", col=col.r[1], lwd=2)
sapply(c(2:n.k), function(x){ lines(time, pore.axis.perm[,x], type="l", col=col.r[x], lwd=2) })
dev.off()
